Category:
    type: "object"
    config:
        description: "Product Category"
        fields:
            id:
                type: "Int"
                description: "The unique ID of the Category."
            name:
                type: "String"
                description: "Name of the Category"
            slug:
                type: "String"
                description: "URL Slug"
            description:
                type: "String"
                description: "Blob to describe the Category"
            subcategory:
                type: "[SubCategory]"
