Query:
    type: object
    config:
        description: "Just the nice way of getting to the products and product details"
        fields:
            SubCategory:
                type: "SubCategory"
                args:
                    id:
                        description: "Resolves using the SubCategory id."
                        type: "Int"
                resolve: "@=resolver('SubCategory', [args])"

            Category:
                type: "Category"
                args:
                    id:
                        description: "Resolves using the Category id. DEFAULT ARGUMENT."
                        type: "Int"
                    slug:
                        description: "Resolves based on URL slug.  If id is passed, this argument will be ignored."
                        type: "String"
                resolve: "@=resolver('Category', [args])"
            # products:
